-- Fill-vs-cancel classification, phase 1 (no engine change).
--
-- The Midnight nullifier events the sync layer delivers have always carried
-- the spending transaction's hash — the STM just discarded it. Storing it
-- makes spends groupable by transaction, which is the discriminator between
-- an offer that settled and one whose coins the maker moved elsewhere:
--
--   settlement is ATOMIC — a fill consumes ALL of an offer's inputs in ONE
--   Midnight transaction. Offer nullifiers spent across different txs, or
--   only partially spent, can therefore never be a fill: that offer was
--   cancelled. (All-in-one-tx remains a heuristic: a maker consolidating
--   those same coins in one personal tx is indistinguishable until phase 2
--   adds output-commitment tracking.)
--
-- Classification happens at READ time, not at archive time: the archive
-- fires on the first nullifier event of a block, before its same-tx siblings
-- are processed. Reads never see that partial state — the whole block
-- commits in one DB transaction — so a read-time rule is race-free where an
-- archive-time rule would misclassify.
--
-- Nullable: rows written before this migration (none — deployments start
-- from zero) or an event without a hash classify conservatively.
ALTER TABLE nullifiers ADD COLUMN IF NOT EXISTS tx_hash TEXT;
